### ISSUE TITLE
Tenemos que hablar, un saludo de Steven ^^

### ISSUE THREAD

**Issue by StevenCastroSC** [romhackhispano/tiovictor.romhackhispano.org#3]
Buenos días estimado Victor. 

No sé si sabes de mi o de mi proyecto. Tal vez si por que la amplitud que ha cogido es importante. Me vas a disculpar que te contacte por Github, encima por este repositorio. Pero como traductores y programadores, tal vez sea la forma mas directa. 

Pagina web: https://stevenelfuegodelvi.wixsite.com/estudiocases

Actualmente conozco un proyecto de doblaje latino de IGStudios, conozco a los responsables. También estoy en esta aventura con DoblajeSpain: 
![image](https://github.com/romhackhispano/tiovictor.romhackhispano.org/assets/123419009/360fe4f7-b774-4b52-8c4a-9e3accc48438)

Como imaginaras, yo mismo he hecho la ingeniería inversa/traducción del juego Resident Evil 4, actualmente en proceso de doblaje.

Te dejo unos videos de prueba/audios. Tenemos un discord. Es uno de los proyectos mas ambiciosos jamás vistos. Youtuber importantes como este:

![image](https://github.com/romhackhispano/tiovictor.romhackhispano.org/assets/123419009/354088a4-12f2-4faa-903b-355ec68c29ae)

Tiene videos de millones de visitas. Otros ya nos han comunicado las ganas que hay del RE4 clásico en Castellano, sin desmerecer lo hecho ya en México anteriormente.

No te he contactado antes por que no ha sido necesario. Pero al haber amplitud en el proyecto (Y al tener a Lorenzo Beteta en el reparto) creo que debería presentar el proyecto a uno de los grandes de esta forma para que este al corriente. El respeto que te tengo es muy importante, tanto como programador como traductor. 

Actualmente soy el responsable, pero un buen lider es aquel que reconoce sus puntos flacos, que sabe rodearse de gente competente y que administrar de la mejor manera posible un equipo. Nos gustaría saber tu opinión. Te dejo mi numero de WhatsApp, creo que la comunidad lo merece. Para ello, y para no publicar mi teléfono, envíame un correo rápido a laboleradelgaming@gmail.com

Eso si, te dejo algunas muestras de las voces, los archivos son licencia de capcom, los comparto si es necesario después en privado, es para que sepa tu opinión y que estemos con toda la comunidad. Y con todo respeto, la comunidad hispana simplemente se llama Tio Victor, por eso en traducción se merece que te contacte. 

https://github.com/romhackhispano/tiovictor.romhackhispano.org/assets/123419009/6dd3740a-57d3-48db-b2a9-9be27c847014

https://github.com/romhackhispano/tiovictor.romhackhispano.org/assets/123419009/0d988013-222b-4724-a0ab-883e5b2cf594

https://github.com/romhackhispano/tiovictor.romhackhispano.org/assets/123419009/15fa6682-03e3-4d92-8d65-aeda8d24b338

Saludos, estoy pendiente.

Steven, responsable de EstudioCases

**Comment by IlDucci** [comment]
No.

Primero: este no es el medio de comunicación apropiado para esta clase de comunicaciones. Tengo mis comentarios del foro y mi email en ciertos lugares que no debería costar encontrar.

Segundo: sí que he oído hablar de tu proyecto. En concreto, de cuando pretendías utilizar las voces clonadas del remake de Resident Evil 4 mediante sistemas de duplicado de voces por LLM de tipo VTS o STS, me da igual. Ya con eso cruzaste una línea roja para mí, aprovechándote del trabajo de compañeros, tanto de profesión (por parte de ADOMA, en el caso del remake de Resident Evil 4) como de afición (por si considerases que los actores de renombre merecen más respeto que los actores de fandub).

Llevo años viendo cómo surgen proyectos de fandub hechos con voces robadas con IA y me repugna ver ese foco de entrada para que la gente lo vaya asimilando como algo normal: el Snatcher en italiano, los juegos para Saturn en francés, los experimentos con gaseosa de Chema von Alexandros... Me niego tajantemente a participar en un proyecto que haya tocado el mundo de las voces por IA, por principios y por respeto a los compañeros de la voz. Si ya las has usado una vez, me tendrás que demostrar con algo más que tres pruebas de voz si no vas a volver a utilizarlas en el futuro o robando otras voces, como he dicho.

De la misma forma y a título preventivo para todo el mundo, ninguno de los proyectos de Traducciones del Tío Víctor permite que se reciclen las voces de sus doblajes, de ninguna manera y bajo ningún concepto, para entrenar, alimentar o utilizar sistemas de voces sintéticas (STS, VTS o cualquier otro sistema futuro). Aunque hablo a título de jefe de proyecto y persona que apalabró dichas grabaciones con los actores, estoy seguro de que la gran mayoría de compañeros que han puesto su voz opinarían lo mismo.

**Comment by StevenCastroSC** [comment]
Buenas tardes estimado Victor.

Agradezco que haya podido enviar el correo y me disculpo en varios puntos.
Yo no estoy aquí para molestar a nadie y menos a usted. Soy muy amistoso y
creo que puedo explicar todo el proyecto desde la perspectiva que estamos
haciendo.

Te respondo con la mejor intención del mundo ^^ Repito que el respeto que
te tengo es muy grande y perdoname por todo error de comunicación tanto
mía como de mi equipo.

Ciertamente, hubo un error de comunicación y de perspectiva entre lo que
quería ser el proyecto y lo que se hizo en un principio. Por suerte, se
paró a tiempo y estuvimos hablando con las voces originales de reparto (RE4
Remake) para pedir perdón. La chica que subió el post lo entendió y borró
todo de X.

Ahora el proyecto cuenta con voces de actores que quieren dar su granito de
arena. El objetivo es doblar, no hacer daño al doblaje. Hay que decir que
Lorenzo Beteta (Voz de Leon Kennedy), entendió todo y aceptó coger un
papel. Va a ser Mike, el chico del helicóptero.

Pedí miles de disculpas y DoblajeSpain también lo entendió.

[image: image.png]

Sé que eres muy inteligente, y una gran persona. Esto es lo único que
explicaría tantos proyectos que has realizado hasta ahora y te doy las
gracias por las horas de diversión.

Creo que las voces que estamos escogiendo y que participan están haciendo
un buen papel. Creo que en ese sentido, lo haremos bien.

No quiero que un proyecto tan bonito y que se va a hacer bien pueda ser
manchado por un error mío que ya no es una realidad.

Eres alguien despierto, sé que sabes mucho de mi, de mi trayectoria
profesional tal vez en el mundo del teatro como técnico, mis servicios en
empresas de informática, mis habilidades de traducción o cualquier otro
aspecto. Si ya tienes mi correo, evidentemente lo tienes todo.

Por eso, quiero dar la oportunidad a este proyecto que ya no usa nada de
esas tecnologías. Supongo que si has tomado el tiempo de responder, es por
que hay algo de interés dentro de la comunidad por doblar juegos.

Hicisteis un trabajo increíble con el code veronica. Se lo merecía.

Te dejo mi whatsapp: +33 6 59 61 05 26 (Prefijo Francés)

Hablando, todos nos entendemos y es más fácil.

Te dejo un ejemplo en archivo de lo que los actores tienen para doblar.
Este archivo tiene errores porque el actor me dice luego las frases donde
corre más para terminar la adaptación.

Lo hago todo de buena fe. No te pido ayuda, pero si creo que el proyecto
necesita que la parte real de la historia, sea conocida y que se ha
cambiado todo.

Tampoco te voy a molestar, miralo y si no, que sepas que este proyecto no
es del mismo calibre de lo que piensas. Creo que si has visto los videos
mandados, es imposible que los actores no sean reales. Estamos todos en
grupo, el ambiente es genial (He prometido a los de Barcelona un
restaurante y tal al final, para que la aventura de doblaje sea divertida)
y doy facilidades.

Si fuera como te piensas, no hubiese contactado contigo y no hubiese dado
todos mis datos.

Te dejo unos archivos adjuntos. Es un placer, de verdad, cuantas horas de
diversión habrás dado durante los proyectos.

Un saludo.

Archivos: https://we.tl/t-p87nJNIkV0

Así se me olvidaba, Capcom me ha indicado que no aprueban ni desaprueban el
mod. Que haga lo que haga seré monitoreado y que si algo molesta, ellos me
lo harán saber.

😊😊😊

**Comment by IlDucci** [comment]
> Buenas tardes estimado Victor.
>Agradezco que haya podido enviar el correo y me disculpo en varios puntos. Yo no estoy aquí para molestar a nadie y menos a usted. Soy muy amistoso y creo que puedo explicar todo el proyecto desde la perspectiva que estamos haciendo.
> Te respondo con la mejor intención del mundo ^^ Repito que el respeto que te tengo es muy grande y perdoname por todo error de comunicación tanto mía como de mi equipo.
> Ciertamente, hubo un error de comunicación y de perspectiva entre lo que quería ser el proyecto y lo que se hizo en un principio. Por suerte, se paró a tiempo y estuvimos hablando con las voces originales de reparto (RE4 Remake) para pedir perdón. La chica que subió el post lo entendió y borró todo de X.
> Ahora el proyecto cuenta con voces de actores que quieren dar su granito de arena. El objetivo es doblar, no hacer daño al doblaje. Hay que decir que Lorenzo Beteta (Voz de Leon Kennedy), entendió todo y aceptó coger un papel. Va a ser Mike, el chico del helicóptero.
> Pedí miles de disculpas y DoblajeSpain también lo entendió.
> [image: image.png]
> Sé que eres muy inteligente, y una gran persona. Esto es lo único que explicaría tantos proyectos que has realizado hasta ahora y te doy las gracias por las horas de diversión.
> Creo que las voces que estamos escogiendo y que participan están haciendo un buen papel. Creo que en ese sentido, lo haremos bien.
> No quiero que un proyecto tan bonito y que se va a hacer bien pueda ser manchado por un error mío que ya no es una realidad.
> Eres alguien despierto, sé que sabes mucho de mi, de mi trayectoria profesional tal vez en el mundo del teatro como técnico, mis servicios en empresas de informática, mis habilidades de traducción o cualquier otro aspecto. Si ya tienes mi correo, evidentemente lo tienes todo.
> Por eso, quiero dar la oportunidad a este proyecto que ya no usa nada de esas tecnologías. Supongo que si has tomado el tiempo de responder, es por que hay algo de interés dentro de la comunidad por doblar juegos.
> Hicisteis un trabajo increíble con el code veronica. Se lo merecía.
> Te dejo mi whatsapp: BORRADO
> Hablando, todos nos entendemos y es más fácil.
> Te dejo un ejemplo en archivo de lo que los actores tienen para doblar. Este archivo tiene errores porque el actor me dice luego las frases donde corre más para terminar la adaptación.
> Lo hago todo de buena fe. No te pido ayuda, pero si creo que el proyecto necesita que la parte real de la historia, sea conocida y que se ha cambiado todo.
> Tampoco te voy a molestar, miralo y si no, que sepas que este proyecto no es del mismo calibre de lo que piensas. Creo que si has visto los videos mandados, es imposible que los actores no sean reales. Estamos todos en grupo, el ambiente es genial (He prometido a los de Barcelona un restaurante y tal al final, para que la aventura de doblaje sea divertida) y doy facilidades.
> Si fuera como te piensas, no hubiese contactado contigo y no hubiese dado todos mis datos.
> Te dejo unos archivos adjuntos. Es un placer, de verdad, cuantas horas de diversión habrás dado durante los proyectos.
> Un saludo. Archivos: https://we.tl/t-p87nJNIkV0
> Así se me olvidaba, Capcom me ha indicado que no aprueban ni desaprueban el mod. Que haga lo que haga seré monitoreado y que si algo molesta, ellos me lo harán saber.
> 😊😊😊

Deberías saber que has contestado al hilo de GitHub y no a mi email personal. Has puesto tus datos personales a la vista de todo el mundo, no solo a mi vista. Edítalo.

Me sigue sin interesar trabajar en tu proyecto. Además, también estoy saturado de cosas que hacer.

Lo único que diré es que las tres muestras que has subido aquí en vídeo pintan bien. Esos tres actores podrían tener un buen futuro por delante.
